### ISSUE TITLE
cannot get elevation in Coordinate Reference System (CRS) WGS84 ?

### ISSUE THREAD

**Issue by edorich** [geomatico/TerrainService#13]
Hallo,, is possible to get elevation from .tif with CRS WGS84?

thanks for your help..

**Comment by oscarfonts** [comment]
As stated in README, "No reprojection is performed, so it is assumed that DEM will be in the same CRS than vector files".
If input data is in WGS84 , TIF should be in WGS84 as well.

The provided sample TIFF is in ETRS89, which is equivalent to WGS84 at the resolutions we are using here.
